'use client'
import { useState } from 'react'
import { X } from 'lucide-react'
import type { Project } from '@/data/projects'
import { ProjectArt } from './ProjectArt'
import { getEmbedUrl, getYoutubeId } from '@/lib/utils'
type Kind='frame'|'motion-design'|'poster'
function LoopMedia({project,kind}:{project:Project;kind:Kind}){if(kind==='motion-design'&&project.videoUrl&&!project.videoUrl.includes('YOUR_')){if(project.videoType==='mp4')return <video className="h-full w-full object-cover" src={project.videoUrl} autoPlay muted loop playsInline/>;const id=getYoutubeId(project.videoUrl);return <iframe className="pointer-events-none h-full w-full border-0" src={`${getEmbedUrl(project)}?autoplay=1&mute=1&controls=0&loop=1&modestbranding=1&rel=0&iv_load_policy=3&disablekb=1&fs=0${id?`&playlist=${id}`:''}`} title={project.title} allow="autoplay"/>}return <ProjectArt project={project}/>} 
export function MediaMarquee({projects,kind}:{projects:Project[];kind:Kind}){const [selected,setSelected]=useState<Project|null>(null);if(!projects.length)return null;const rows=[projects.filter((_,i)=>i%2===0),projects.filter((_,i)=>i%2===1)];const clickable=kind==='frame'||kind==='poster';return <><div className="media-marquee space-y-3 overflow-hidden py-1">{rows.map((row,index)=><div key={index} className={`media-track ${index===1?'media-track-reverse':''}`}>{[...row,...row].map((project,i)=><button key={`${project.id}-${i}`} onClick={()=>clickable?setSelected(project):window.location.assign(`/watch/${project.slug||project.id}`)} className={`media-tile ${kind==='poster'?'media-tile-poster':''} focus group ${clickable?'cursor-zoom-in':'cursor-pointer'}`}><LoopMedia project={project} kind={kind}/>{kind==='frame'&&<span className="absolute inset-x-2 bottom-2 truncate text-left text-xs font-bold text-white drop-shadow-lg">{project.title}</span>}</button>)}</div>)}</div>{selected&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/80 p-4" onClick={()=>setSelected(null)}><div className="relative w-full max-w-3xl" onClick={e=>e.stopPropagation()}><button aria-label="Close design" onClick={()=>setSelected(null)} className="absolute -right-2 -top-12 rounded-full bg-white p-2 text-black"><X size={20}/></button><div className={`${selected.type==='poster'?'aspect-[1/1.414]':'aspect-video'} overflow-hidden rounded-xl bg-black`}><ProjectArt project={selected}/></div><h3 className="mt-3 text-lg font-bold">{selected.title}</h3></div></div>}</>}
