'use client'

import { useState } from 'react'
import { ArrowUpRight, CheckCircle, Sparkles } from 'lucide-react'
import { siteConfig } from '@/data/site'
import { experience, tools } from '@/data/profile'

export function ChannelHeader({settings=siteConfig}:{settings?:typeof siteConfig}){
  const [pos,setPos]=useState({x:70,y:40})
  return <section onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();setPos({x:((e.clientX-r.left)/r.width)*100,y:((e.clientY-r.top)/r.height)*100})}} className="hero-interactive relative mb-4 min-h-[520px] overflow-hidden rounded-xl border border-[var(--line)] bg-[#121212] md:min-h-[560px]" style={{'--mx':`${pos.x}%`,'--my':`${pos.y}%`} as React.CSSProperties}>
    <div className="hero-abstract-bg absolute inset-0 opacity-75"/><div className="hero-glow absolute inset-0"/>
    <div className="relative p-4 sm:p-6 md:p-8">
      <div className="flex flex-col items-center gap-4 text-center sm:flex-row sm:items-center sm:gap-5 sm:text-left"><div className="relative mt-1 flex aspect-square h-20 w-20 shrink-0 items-center justify-center overflow-hidden rounded-full bg-black shadow-2xl sm:h-24 sm:w-24 md:h-28 md:w-28">{settings.profileImageUrl?<img src={settings.profileImageUrl} alt={settings.name} className="block h-full w-full scale-[1.14] object-cover object-center"/>:<><div className="h-20 w-14 rounded-t-[50%] bg-zinc-950"/><div className="absolute h-14 w-11 translate-y-[-25px] rounded-[45%] bg-[#a77659]"/></>}</div><div className="min-w-0 max-w-[680px] flex-1"><div className="flex flex-wrap items-center justify-center gap-2 sm:justify-start"><h1 className="min-w-0 break-words text-[24px] font-bold tracking-tight sm:text-[28px] md:text-[34px]">{settings.name}</h1><CheckCircle size={17} fill="white" className="shrink-0 text-black"/></div><p className="mt-0.5 break-words text-xs md:text-sm">{settings.handle} <span className="px-1.5">•</span> {settings.channelSubtitle}</p><p className="mt-2 text-sm md:text-base">{settings.role}</p><p className="mt-2 max-w-[600px] text-xs leading-5 text-zinc-200 md:text-sm">{settings.bio}</p><div className="mt-4 flex flex-wrap justify-center gap-2 sm:justify-start"><button className="focus rounded-full bg-white px-5 py-2 text-xs font-bold text-black transition hover:-translate-y-0.5 hover:bg-[#DF1730] hover:text-white">Follow</button>{settings.contactEnabled?<a href="/contact" className="focus inline-flex items-center gap-1 rounded-full border border-white/10 bg-black/25 px-5 py-2 text-xs font-bold transition hover:-translate-y-0.5 hover:border-white/40">Hire Me <ArrowUpRight size={13}/></a>:<button type="button" disabled aria-disabled="true" className="focus inline-flex items-center gap-1 rounded-full border border-white/10 bg-black/25 px-5 py-2 text-xs font-bold">Hire Me <ArrowUpRight size={13}/></button>}</div></div></div>
      <div className="mt-8 grid gap-6 lg:mt-10 lg:grid-cols-[1.15fr_.85fr]"><div><p className="flex items-center gap-2 text-xs font-bold tracking-[.18em] text-[#DF1730]"><Sparkles size={14}/> TOOLKIT IN MOTION</p><p className="mt-2 max-w-xl text-sm leading-6 text-zinc-300">Turning a blank timeline into a visual story with a toolkit built for rhythm, detail and feeling.</p><div className="mt-5 flex flex-wrap gap-2">{tools.map((tool,i)=><span key={tool} className="tool-pill" style={{'--i':i} as React.CSSProperties}>{tool}</span>)}</div></div><div><p className="text-xs font-bold tracking-[.18em] text-[#DF1730]">THE JOURNEY SO FAR</p><div className="mt-3 space-y-2">{experience.map((item,i)=><div key={item.company} className="experience-mini" style={{'--i':i} as React.CSSProperties}><span className="text-xs font-bold text-[#DF1730]">0{i+1}</span><div className="min-w-0"><b className="block text-sm">{item.role}</b><span className="text-xs text-zinc-400">{item.company} · {item.period}</span></div></div>)}</div></div></div>
    </div>
  </section>
}
