'use server'
import { revalidatePath } from 'next/cache'
import { sanityClient } from '@/sanity/client'
function writer(){const token=process.env.SANITY_API_WRITE_TOKEN;if(!token)throw new Error('Set SANITY_API_WRITE_TOKEN in your environment to save changes.');return sanityClient.withConfig({token,useCdn:false})}
const val=(f:FormData,k:string)=>String(f.get(k)||'').trim()
async function storedImage(client:any,f:FormData,fileKey:string,urlKey:string){const current=val(f,urlKey);const file=f.get(fileKey);if(!(file instanceof File)||file.size===0)return current;const asset=await client.assets.upload('image',Buffer.from(await file.arrayBuffer()),{filename:file.name});return asset.url||current}
export async function saveSettings(f:FormData){try{const c=writer();const id=await c.fetch<string|undefined>(`*[_type == "siteSettings"][0]._id`);const [logoUrl,profileImageUrl,heroBackgroundUrl,aboutImageUrl]=await Promise.all([storedImage(c,f,'logoFile','logoUrl'),storedImage(c,f,'profileImageFile','profileImageUrl'),storedImage(c,f,'heroBackgroundFile','heroBackgroundUrl'),storedImage(c,f,'aboutImageFile','aboutImageUrl')]);await c.createOrReplace({_id:id||'siteSettings',_type:'siteSettings',name:val(f,'name'),handle:val(f,'handle'),role:val(f,'role'),bio:val(f,'bio'),channelSubtitle:val(f,'channelSubtitle'),aboutTitle:val(f,'aboutTitle'),aboutBody:val(f,'aboutBody'),contactTitle:val(f,'contactTitle'),contactBody:val(f,'contactBody'),logoUrl,profileImageUrl,heroBackgroundUrl,aboutImageUrl,email:val(f,'email'),instagram:val(f,'instagram'),youtube:val(f,'youtube'),behance:val(f,'behance'),linkedin:val(f,'linkedin'),contactEnabled:f.get('contactEnabled')==='on'});revalidatePath('/');revalidatePath('/about');revalidatePath('/contact');return {ok:true}}catch(e){return {ok:false,error:e instanceof Error?e.message:'Unable to save settings.'}}}
export async function saveProject(f:FormData){try{const c=writer();const id=val(f,'id')||crypto.randomUUID();const url=val(f,'videoUrl');const current=await c.fetch<{duration?:string;likes?:number;thumbnail?:string;sortOrder?:number}|null>(`*[_id == $id][0]{duration,likes,thumbnail,sortOrder}`,{id});const thumbnail=await storedImage(c,f,'thumbnailFile','thumbnailUrl');await c.createOrReplace({_id:id,_type:'project',title:val(f,'title'),slug:{_type:'slug',current:id},client:val(f,'client'),year:Number(val(f,'year'))||new Date().getFullYear(),category:val(f,'category'),type:val(f,'type'),thumbnail:thumbnail||current?.thumbnail||'',videoUrl:url,videoType:url.includes('vimeo.com')?'vimeo':url.endsWith('.mp4')?'mp4':'youtube',duration:current?.duration,likes:current?.likes||0,sortOrder:Number(val(f,'sortOrder'))||current?.sortOrder||9999,views:val(f,'views'),description:val(f,'description'),tags:val(f,'tags').split(',').map(x=>x.trim()).filter(Boolean),accent:val(f,'accent')||'violet'});revalidatePath('/');revalidatePath(`/watch/${id}`);return {ok:true}}catch(e){return {ok:false,error:e instanceof Error?e.message:'Unable to save project.'}}}
export async function deleteProject(id:string){try{if(!id)throw new Error('This project has not been saved yet.');await writer().delete(id);revalidatePath('/');return {ok:true}}catch(e){return {ok:false,error:e instanceof Error?e.message:'Unable to delete project.'}}}
