'use client'

import { useState } from 'react'
import type { Project, ProjectType } from '@/data/projects'
import type { siteConfig } from '@/data/site'
import { deleteProject, saveProject, saveSettings } from './actions'

type Result = {ok:boolean;error?:string}

function Field({name,label,value,area=false,type='text'}:{name:string;label:string;value?:string|number;area?:boolean;type?:string}){
  return <label className="block text-xs font-medium text-zinc-400">{label}{area?<textarea name={name} defaultValue={value} className="mt-1.5 min-h-24 w-full rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-white outline-none focus:border-red-400"/>:<input name={name} type={type} defaultValue={value} className="mt-1.5 w-full rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-white outline-none focus:border-red-400"/>}</label>
}

function FileField({name,label,value}:{name:string;label:string;value?:string}){
  return <label className="block text-xs font-medium text-zinc-400">{label}<input type="hidden" name={name.replace('File','Url')} value={value||''}/><input name={name} type="file" accept="image/*" className="mt-1.5 block w-full rounded-md border border-dashed border-zinc-700 bg-zinc-950 px-3 py-2 text-xs text-zinc-300 file:mr-3 file:rounded file:border-0 file:bg-zinc-700 file:px-2 file:py-1 file:text-xs file:text-white"/>{value&&<span className="mt-1 block truncate text-[10px] text-zinc-500">Stored image: {value}</span>}</label>
}

const labels:Record<ProjectType,string> = {'long-form':'Long-form','short-form':'Short-form','motion-design':'Motion Design',frame:'My Frames',poster:'Posters'}

export function Editor({projects,settings}:{projects:Project[];settings:typeof siteConfig}){
  const [message,setMessage] = useState('')
  const [selected,setSelected] = useState<Project|null>(projects[0]||null)
  const submit = async(action:(f:FormData)=>Promise<Result>,f:FormData) => { const result=await action(f); setMessage(result.ok?'Saved — refresh the public page to see the update.':result.error||'Could not save.') }
  const grouped = (Object.keys(labels) as ProjectType[]).map(type=>({type,items:projects.filter(p=>p.type===type)}))
  const remove = async() => { if(!selected?.id||!window.confirm(`Delete “${selected.title}”? This cannot be undone.`)) return; const result=await deleteProject(selected.id); setMessage(result.ok?'Deleted — refresh the public page to see the update.':result.error||'Could not delete.'); if(result.ok)setSelected(null) }

  return <main className="min-h-screen bg-[#0c0c0d] p-5 text-white md:p-9"><div className="mx-auto max-w-6xl">
    <header className="mb-8 flex flex-wrap items-center justify-between gap-4 border-b border-zinc-800 pb-5"><div><p className="text-xs font-bold tracking-[.18em] text-red-400">PRIVATE AREA</p><h1 className="mt-1 text-2xl font-bold">Portfolio editor</h1></div><a href="/" target="_blank" className="rounded-lg border border-zinc-700 px-4 py-2 text-sm font-semibold hover:bg-zinc-800">View public site ↗</a></header>
    {message&&<p className={`mb-5 rounded-lg border border-zinc-800 bg-zinc-900 p-3 text-sm ${message.startsWith('Saved')||message.startsWith('Deleted')?'text-emerald-400':'text-red-300'}`}>{message}</p>}
    <section className="rounded-xl border border-zinc-800 bg-[#171719] p-5"><h2 className="text-lg font-bold">Site text, images & links</h2><p className="mt-1 text-xs text-zinc-500">Uploaded images are stored in Sanity assets and remain available independently of your device.</p><label className="mt-5 flex items-start gap-3 rounded-lg border border-red-500/50 bg-red-500/10 p-4 text-xs text-zinc-300"><input name="contactEnabled" type="checkbox" defaultChecked={settings.contactEnabled !== false} className="mt-0.5 h-4 w-4 accent-red-500"/><span><b className="block text-sm text-white">Contact Me / More section</b><span className="mt-1 block text-zinc-400">Turn off to hide More, Connect, and Contact Me from the sidebar and disable every Hire Me button.</span></span></label><form action={f=>submit(saveSettings,f)} encType="multipart/form-data" className="mt-5 grid gap-4 md:grid-cols-2">
      <Field name="name" label="Name" value={settings.name}/><Field name="handle" label="Handle" value={settings.handle}/><Field name="role" label="Role line" value={settings.role}/><Field name="channelSubtitle" label="Homepage channel subtitle" value={settings.channelSubtitle}/><div className="md:col-span-2"><Field name="bio" label="Homepage bio" value={settings.bio} area/></div><Field name="aboutTitle" label="About title" value={settings.aboutTitle}/><Field name="contactTitle" label="Contact title" value={settings.contactTitle}/><div className="md:col-span-2"><Field name="aboutBody" label="About text" value={settings.aboutBody} area/></div><div className="md:col-span-2"><Field name="contactBody" label="Contact text" value={settings.contactBody} area/></div><FileField name="logoFile" label="Logo image" value={settings.logoUrl}/><FileField name="profileImageFile" label="Profile picture" value={settings.profileImageUrl}/><FileField name="aboutImageFile" label="About page image" value={settings.aboutImageUrl}/><div className="md:col-span-2"><FileField name="heroBackgroundFile" label="Homepage hero image" value={settings.heroBackgroundUrl}/></div>{['email','instagram','youtube','behance','linkedin'].map(key=><Field key={key} name={key} label={key[0].toUpperCase()+key.slice(1)} value={settings[key as keyof typeof settings] as string | undefined}/>) }<button className="w-fit rounded-lg bg-red-500 px-4 py-2 text-sm font-bold">Save site settings</button>
    </form></section>
    <section className="mt-7 grid gap-6 lg:grid-cols-[290px_1fr]"><aside className="rounded-xl border border-zinc-800 bg-[#171719] p-3"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold">Projects by section</h2><button type="button" onClick={()=>setSelected({id:'',slug:'',title:'',year:new Date().getFullYear(),category:'',type:'long-form',thumbnail:'',accent:'violet'})} className="rounded bg-zinc-800 px-2 py-1 text-xs font-bold">+ New</button></div><div className="max-h-[620px] space-y-4 overflow-y-auto">{grouped.map(group=><div key={group.type}><p className="px-2 pb-1 text-[10px] font-bold tracking-[.16em] text-red-400">{labels[group.type]}</p><div className="space-y-1">{group.items.map(p=><button type="button" key={p.id} onClick={()=>setSelected(p)} className={`w-full rounded px-3 py-2 text-left text-sm ${selected?.id===p.id?'bg-red-500/20 text-red-200':'hover:bg-zinc-800'}`}><b className="block truncate">{p.title}</b><span className="text-xs text-zinc-500">Order {p.sortOrder??'auto'}</span></button>)}</div></div>)}</div></aside>{selected&&<ProjectForm project={selected} onSave={submit} onDelete={remove}/>}</section>
  </div></main>
}

function ProjectForm({project,onSave,onDelete}:{project:Project;onSave:(a:(f:FormData)=>Promise<Result>,f:FormData)=>Promise<void>;onDelete:()=>Promise<void>}){
  return <section className="rounded-xl border border-zinc-800 bg-[#171719] p-5"><h2 className="text-lg font-bold">{project.id?'Edit project':'New project'}</h2><p className="mt-1 text-xs text-zinc-500">Page URL, duration and likes are automatic or locked. Lower display order numbers appear first in that section.</p><form action={f=>onSave(saveProject,f)} encType="multipart/form-data" className="mt-5 grid gap-4 md:grid-cols-2"><input type="hidden" name="id" value={project.id}/><Field name="title" label="Title" value={project.title}/><Field name="client" label="Client" value={project.client}/><Field name="year" label="Year" type="number" value={project.year}/><Field name="sortOrder" label="Display order" type="number" value={project.sortOrder}/><Field name="category" label="Category" value={project.category}/><label className="block text-xs font-medium text-zinc-400">Portfolio shelf<select name="type" defaultValue={project.type} className="mt-1.5 w-full rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-white"><option value="long-form">Long-form</option><option value="short-form">Short-form</option><option value="motion-design">Motion design</option><option value="frame">My Frames</option><option value="poster">Posters</option></select></label><Field name="videoUrl" label="Video URL" value={project.videoUrl}/><FileField name="thumbnailFile" label="Static frame / poster image" value={project.thumbnail}/><Field name="views" label="Views label" value={project.views}/><Field name="accent" label="Fallback artwork color" value={project.accent}/><Field name="tags" label="Tags (comma-separated)" value={project.tags?.join(', ')}/><div className="md:col-span-2"><Field name="description" label="Project description" value={project.description} area/></div><div className="flex flex-wrap gap-3"><button className="w-fit rounded-lg bg-red-500 px-4 py-2 text-sm font-bold">Save project</button>{project.id&&<button type="button" onClick={onDelete} className="w-fit rounded-lg border border-red-900 px-4 py-2 text-sm font-bold text-red-300 hover:bg-red-950">Delete project</button>}</div></form></section>
}
